
GRAPH = {'vintage': ['sf', 'san'],
 'google': ['journey'],
 'restaurant': ['sushi', 'san', 'near'],
 'sushi': ['restaurant'],
 'san': ['restaurant', 'vintage'],
 'harvard': [],
 'princess': ['polly'],
 'polly': ['princess'],
 'near': ['restaurant'],
 'sf': ['vintage'],
 'movie': [],
 'tattoo': ['poker'],
 'food': ['asian'],
 'asian': ['food'],
 'check': [],
 'set': [],
 'target': [],
 'pant': [],
 'tech': [],
 'poker': ['tattoo'],
 'playing': [],
 'quantitative': [],
 'social': ['visualization'],
 'visualization': ['social', 'node'],
 'node': ['visualization'],
 'journey': ['google']}

SIZES = {'vintage': 11,
 'google': 10,
 'restaurant': 18,
 'sushi': 15,
 'san': 31,
 'harvard': 19,
 'princess': 13,
 'polly': 12,
 'near': 18,
 'sf': 13,
 'movie': 12,
 'tattoo': 14,
 'food': 26,
 'asian': 15,
 'check': 10,
 'set': 12,
 'target': 10,
 'pant': 15,
 'tech': 14,
 'poker': 17,
 'playing': 13,
 'quantitative': 10,
 'social': 11,
 'visualization': 27,
 'node': 12,
 'journey': 11}