
# GRAPH = {'vintage': ['sf', 'san'],
#  'google': ['journey'],
#  'restaurant': ['sushi', 'san', 'near'],
#  'sushi': ['restaurant'],
#  'san': ['restaurant', 'vintage'],
#  'harvard': [],
#  'princess': ['polly'],
#  'polly': ['princess'],
#  'near': ['restaurant'],
#  'sf': ['vintage'],
#  'movie': [],
#  'tattoo': ['poker'],
#  'food': ['asian'],
#  'asian': ['food'],
#  'check': [],
#  'set': [],
#  'target': [],
#  'pant': [],
#  'tech': [],
#  'poker': ['tattoo'],
#  'playing': [],
#  'quantitative': [],
#  'social': ['visualization'],
#  'visualization': ['social', 'node'],
#  'node': ['visualization'],
#  'journey': ['google']}

# SIZES = {'vintage': 11,
#  'google': 10,
#  'restaurant': 18,
#  'sushi': 15,
#  'san': 31,
#  'harvard': 19,
#  'princess': 13,
#  'polly': 12,
#  'near': 18,
#  'sf': 13,
#  'movie': 12,
#  'tattoo': 14,
#  'food': 26,
#  'asian': 15,
#  'check': 10,
#  'set': 12,
#  'target': 10,
#  'pant': 15,
#  'tech': 14,
#  'poker': 17,
#  'playing': 13,
#  'quantitative': 10,
#  'social': 11,
#  'visualization': 27,
#  'node': 12,
#  'journey': 11}

# GRAPH = {'harvard': ['mit', 'internship'],
#     'company': ['word', 'movie'],
#     'bank': ['credit', 'id'],
#     'pant': ['polly', 'set'],
#     'card': ['playing'],
#     'san': ['market', 'bagel'],
#     'food': ['sushi'],
#     'google': ['chrome', 'journey'],
#     'visualization': ['graph'],
#     'business': ['consulting', 'analysis'],
#     'mit': ['harvard'],
#     'internship': ['harvard', 'computer', 'program'],
#     'movie': ['spotify', 'company', 'snowpiercer'],
#     'word': ['blue', 'company', 'yayoi'],
#     'id': ['bank'],
#     'credit': ['airline', 'bank'],
#     'set': ['ribbed', 'pant', 'bodysuit'],
#     'polly': ['sweater', 'sophia', 'pant'],
#     'playing': ['card'],
#     'bagel': ['san'],
#     'market': ['near', 'cafe', 'san'],
#     'sushi': ['food'],
#     'journey': ['google'],
#     'chrome': ['google'],
#     'graph': ['ppc', 'visualization'],
#     'analysis': ['business'],
#     'consulting': ['quantitative', 'business'],
#     'computer': ['internship'],
#     'program': ['internship'],
#     'spotify': ['movie'],
#     'snowpiercer': ['movie'],
#     'yayoi': ['word', 'brandy', 'tara'],
#     'blue': ['word', 'book', 'table'],
#     'airline': ['credit'],
#     'bodysuit': ['set', 'dress', 'earring'],
#     'ribbed': ['set'],
#     'sophia': ['polly'],
#     'sweater': ['polly'],
#     'cafe': ['market'],
#     'near': ['market'],
#     'ppc': ['graph'],
#     'quantitative': ['consulting'],
#     'brandy': ['yayoi'],
#     'tara': ['yayoi'],
#     'book': ['blue'],
#     'table': ['blue'],
#     'dress': ['bodysuit'],
#     'earring': ['bodysuit']}

# SIZES = {'harvard': 27,
# 'company': 125,
# 'bank': 37,
# 'pant': 40,
# 'card': 14,
# 'san': 58,
# 'food': 39,
# 'google': 22,
# 'visualization': 10,
# 'business': 9,
# 'mit': 17,
# 'internship': 9,
# 'movie': 19,
# 'word': 21,
# 'id': 13,
# 'credit': 14,
# 'set': 24,
# 'polly': 15,
# 'playing': 13,
# 'bagel': 10,
# 'market': 13,
# 'sushi': 15,
# 'journey': 15,
# 'chrome': 14,
# 'graph': 9,
# 'analysis': 13,
# 'consulting': 11,
# 'computer': 11,
# 'program': 12,
# 'spotify': 5,
# 'snowpiercer': 7,
# 'yayoi': 26,
# 'blue': 23,
# 'airline': 12,
# 'bodysuit': 8,
# 'ribbed': 10,
# 'sophia': 6,
# 'sweater': 7,
# 'cafe': 10,
# 'near': 17,
# 'ppc': 1,
# 'quantitative': 10,
# 'brandy': 12,
# 'tara': 19,
# 'book': 16,
# 'table': 4,
# 'dress': 14,
# 'earring': 10}

GRAPH = {'belt': [],
 'jacket': ['thml'],
 'lyric': ['sydel', 'imagen'],
 'cvsz': [],
 'weather': ['summer', 'statue'],
 'plantz': ['courtyardbymarriottnearallstonbostonmaz',
  'comedrecreationcenterataddamsparkz'],
 'harvard': ['graphology', 'google'],
 'chicago': ['near', 'hotel'],
 'python': ['module'],
 'derrick': ['white', 'jenisz', 'revel'],
 'thml': ['jacket'],
 'imagen': ['liang', 'lyric', 'nuro'],
 'sydel': ['aa', 'lyric', 'electric'],
 'statue': ['weather'],
 'summer': ['festival', 'weather'],
 'comedrecreationcenterataddamsparkz': ['plantzdatamb',
  'plantz',
  'yoganearcambridgemaz'],
 'courtyardbymarriottnearallstonbostonmaz': ['plantz',
  'quincystbrooklynnyz',
  'grocerywestloopz'],
 'graphology': ['harvard', 'visualization', 'graph'],
 'google': ['harvard', 'ai', 'policy'],
 'hotel': ['chicago'],
 'near': ['chicago', 'place', 'bar'],
 'module': ['python', 'cache', 'github', 'named'],
 'white': ['derrick', 'wife'],
 'jenisz': ['kendallmarriottz', 'derrick', 'brandes'],
 'revel': ['pennstationz', 'derrick', 'saladnearbyz'],
 'liang': ['imagen'],
 'nuro': ['swift', 'imagen', 'celtic'],
 'electric': ['sydel'],
 'aa': ['sydel'],
 'festival': ['summer'],
 'plantzdatamb': ['vaticinvestmentsnewyorkzdatamb',
  'urbanoutfitterszdatamb',
  'soulcyclechicagozdatamb',
  'comedrecreationcenterataddamsparkz'],
 'yoganearcambridgemaz': ['comedrecreationcenterataddamsparkz'],
 'grocerywestloopz': ['courtyardbymarriottnearallstonbostonmaz'],
 'quincystbrooklynnyz': ['courtyardbymarriottnearallstonbostonmaz'],
 'graph': ['graphology'],
 'visualization': ['graphology'],
 'policy': ['zoom', 'trading', 'google'],
 'ai': ['goodreads', 'pulse', 'google'],
 'bar': ['near'],
 'place': ['near'],
 'cache': ['module'],
 'named': ['module'],
 'github': ['module'],
 'wife': ['white'],
 'brandes': ['jenisz'],
 'kendallmarriottz': ['jenisz'],
 'saladnearbyz': ['coffeenearmez', 'revel', 'brunchz'],
 'pennstationz': ['revel'],
 'celtic': ['nuro'],
 'swift': ['warrior', 'nuro', 'illa'],
 'soulcyclechicagozdatamb': ['plantzdatamb'],
 'vaticinvestmentsnewyorkzdatamb': ['plantzdatamb'],
 'urbanoutfitterszdatamb': ['plantzdatamb'],
 'zoom': ['policy'],
 'trading': ['policy', 'vatic', 'rate'],
 'goodreads': ['ai', 'tool', 'code'],
 'pulse': ['ai'],
 'brunchz': ['saladnearbyz'],
 'coffeenearmez': ['bobabellevuez', 'rauschenberg', 'saladnearbyz'],
 'illa': ['van', 'swift', 'wok'],
 'warrior': ['swift'],
 'vatic': ['trading'],
 'rate': ['trading'],
 'tool': ['goodreads'],
 'code': ['case', 'way', 'goodreads'],
 'rauschenberg': ['coffeenearmez'],
 'bobabellevuez': ['coffeenearmez'],
 'wok': ['illa'],
 'van': ['illa'],
 'way': ['code'],
 'case': ['code']}

SIZES = {'belt': 36,
 'jacket': 2,
 'lyric': 165,
 'cvsz': 40,
 'weather': 25,
 'plantz': 137,
 'harvard': 46,
 'chicago': 131,
 'python': 26,
 'derrick': 137,
 'thml': 9,
 'imagen': 17,
 'sydel': 11,
 'statue': 13,
 'summer': 13,
 'comedrecreationcenterataddamsparkz': 30,
 'courtyardbymarriottnearallstonbostonmaz': 18,
 'graphology': 15,
 'google': 42,
 'hotel': 23,
 'near': 6,
 'module': 21,
 'white': 2,
 'jenisz': 21,
 'revel': 11,
 'liang': 18,
 'nuro': 67,
 'electric': 8,
 'aa': 4,
 'festival': 12,
 'plantzdatamb': 36,
 'yoganearcambridgemaz': 9,
 'grocerywestloopz': 6,
 'quincystbrooklynnyz': 1,
 'graph': 5,
 'visualization': 6,
 'policy': 22,
 'ai': 19,
 'bar': 8,
 'place': 14,
 'cache': 4,
 'named': 11,
 'github': 6,
 'wife': 18,
 'brandes': 13,
 'kendallmarriottz': 12,
 'saladnearbyz': 12,
 'pennstationz': 10,
 'celtic': 10,
 'swift': 14,
 'soulcyclechicagozdatamb': 16,
 'vaticinvestmentsnewyorkzdatamb': 7,
 'urbanoutfitterszdatamb': 13,
 'zoom': 9,
 'trading': 15,
 'goodreads': 10,
 'pulse': 9,
 'brunchz': 11,
 'coffeenearmez': 9,
 'illa': 5,
 'warrior': 10,
 'vatic': 6,
 'rate': 2,
 'tool': 8,
 'code': 8,
 'rauschenberg': 8,
 'bobabellevuez': 8,
 'wok': 9,
 'van': 7,
 'way': 6,
 'case': 6}